# Generated by Django 4.2 on 2023-05-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_rename_author_id_answers_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
