# Generated by Django 4.2 on 2023-05-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_questions_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
