# Generated by Django 4.2 on 2023-05-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_answers_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to='askme.answers', verbose_name='Answer'),
        ),
    ]
