# Generated by Django 4.2 on 2023-05-08 14:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0005_alter_likes_answer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questions',
            managers=[
                ('hot', django.db.models.manager.Manager()),
            ],
        ),
    ]
